### ISSUE TITLE
reassign returns `never` for input of a testGen if one of the input generators has no parameters (or is undefined).

### ISSUE THREAD

**Issue by AndoGhevian** [LeshaTat/builder-example#1]
When using reassign, the type of the returned testGen is `never` if one of the input generators does not have parameters. This happens because in the implementation of reassign `Parameters<( ) => any>` returns an empty array `[]` whose first element is `undefined`. When used in this way, the intersection of the union type with the `undefined` returns `never`.

#### Reproduction:
We can simply take provided example which is already broken:
```
export const App = Object.assign(buildApp(deps), { 
  deps,
  testGen: reassign(buildApp, {
    useListOne: nest("list1", useListFakeGen),
    useListTwo: nest("list2", useListFakeGen),
    ListGen: nest("listTestId", ListGen.fakeGen),
    ListItemComponent: () => deps.ListItemComponent // Here is the problem!!!
  })
})
```
Here you will get a testGen type:
`(input: OptionalNullable<never>) => () => JSX.Element`

#### Proposal:
I propose a solution to exclude the types undefined | null | never when calculating parameters union of input generators:
```
export const reassign = <D extends Record<string, any>, O, DG extends {
  [K in keyof D]: (input: any) => D[K]
}>(
  fn: (input: D) => O,
  gens: DG
) => 
(input: OptionalNullable<UnionToIntersection<
  Exclude<Parameters<DG[keyof D]>[0], undefined | null | never>
>>): O => {
  return fn(Object.keys(gens).reduce((acc, key) => {
    acc[key] = gens[key](input)
    return acc
  }, {} as any))
}
```
#### Workaround:
Another possible solution is to always include the parameter `input: {}` in input generators, unfortunately I can’t achieve the enforcement for this type.

**Comment by LeshaTat** [comment]
Thanks! I added a hotfix with a `fixed(obj)` function to handle this case while preserving types.

However, this issue could lead to hard-to-detect bugs, so it’s better to incorporate your solution into the code. Feel free to submit a PR!

**Comment by AndoGhevian** [comment]
Here is the fix i proposed:
https://github.com/LeshaTat/local-di-example/pull/2
